PORTNAME	= openarena
PKGNAMESUFFIX	= -server
PORTREVISION	= 18.1

MAINTAINER	= ports@FreeBSD.org
COMMENT		= OpenArena dedicated server

LICENSE		= GPLv2

MASTERDIR	= ${.CURDIR}/../${PORTNAME}

IOQ3		= SERVER
USE_RC_SUBR	= ioq3ded

.include "${MASTERDIR}/Makefile"
