PORTNAME	= openarena
PKGNAMESUFFIX	= -server

MAINTAINER	= ports@FreeBSD.org
COMMENT		= OpenArena dedicated server

MASTERDIR	= ${.CURDIR}/../${PORTNAME}

IOQ3		= SERVER
USE_RC_SUBR	= ioq3ded

.include "${MASTERDIR}/Makefile"
