PORTNAME	= xonotic
PKGNAMESUFFIX	= -server

MAINTAINER	= pierre.gnaedig@mailoo.org
COMMENT		= Xonotic dedicated server port

MASTERDIR	= ${.CURDIR}/../${PORTNAME}

OPTIONS_EXCLUDE	= CLIENT

.include "${MASTERDIR}/Makefile"
