PORTNAME		= mfoc
PORTVERSION		= 0.10.7
PORTREVISION		= 1
DISTVERSIONPREFIX	= ${PORTNAME}-
COMMENT			= MIFARE classic offline cracker
CATEGORIES		= security
MAINTAINER		= pierre.gnaedig@mailoo.org
GH_ACCOUNT		= nfc-tools

USE_GITHUB		= yes
USES			= autoreconf
GNU_CONFIGURE		= yes

DEPENDS			= libnfc:devel/libnfc

.include <bsd.port.mk>
