PORTNAME	= nexuiz
PKGNAMESUFFIX	= -server

MAINTAINER	= ports@FreeBSD.org
COMMENT		= Nexuiz classic dedicated server
LICENSE		= GPLv2

MASTERDIR 	= ${.CURDIR}/../${PORTNAME}

OPTIONS_DEFAULT	= MAPPACK DEDICATED

.include "${MASTERDIR}/Makefile"
